# Generated by Django 5.0 on 2025-08-18 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_first_name_alter_user_last_name"),
        ("agents", "0003_alter_agent_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_conversations", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("unique_customers", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "whatsapp_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sms_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("voice_minutes", models.IntegerField(default=0)),
                (
                    "voice_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={"unique_together": {("organization", "date")},},
        ),
        migrations.CreateModel(
            name="HourlyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("total_conversations", models.IntegerField(default=0)),
                ("active_conversations", models.IntegerField(default=0)),
                ("ended_conversations", models.IntegerField(default=0)),
                ("handed_off_conversations", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("ai_messages", models.IntegerField(default=0)),
                ("human_messages", models.IntegerField(default=0)),
                ("customer_messages", models.IntegerField(default=0)),
                ("avg_response_time_seconds", models.FloatField(default=0)),
                ("avg_conversation_duration_minutes", models.FloatField(default=0)),
                ("avg_messages_per_conversation", models.FloatField(default=0)),
                ("whatsapp_conversations", models.IntegerField(default=0)),
                ("sms_conversations", models.IntegerField(default=0)),
                ("voice_conversations", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agents.agent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "timestamp"],
                        name="analytics_h_organiz_30f20c_idx",
                    ),
                    models.Index(
                        fields=["agent", "timestamp"],
                        name="analytics_h_agent_i_f80953_idx",
                    ),
                ],
                "unique_together": {("organization", "agent", "timestamp")},
            },
        ),
    ]
