# Generated by Django 5.0 on 2025-08-09 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "system_prompt",
                    models.TextField(help_text="Base instructions for the AI agent"),
                ),
                (
                    "personality_traits",
                    models.TextField(help_text="How should the agent behave?"),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=500)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4", "GPT-4"),
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                        ],
                        default="gpt-4",
                        max_length=50,
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        blank=True, help_text="ElevenLabs voice ID", max_length=100
                    ),
                ),
                (
                    "voice_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Voice configuration settings",
                    ),
                ),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                ("sms_enabled", models.BooleanField(default=False)),
                (
                    "sms_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                ("voice_enabled", models.BooleanField(default=False)),
                (
                    "voice_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                (
                    "response_delay_seconds",
                    models.IntegerField(default=2, help_text="Simulate typing delay"),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "business_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"monday": {"start": "09:00", "end": "17:00"}, ...}',
                    ),
                ),
                ("out_of_hours_message", models.TextField(blank=True)),
                (
                    "welcome_message",
                    models.TextField(
                        default="Hello! How can I help you today?",
                        help_text="Initial greeting message",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_test_mode", models.BooleanField(default=False)),
                ("total_conversations", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("average_conversation_duration", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={"db_table": "agents", "ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="AgentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("customer_service", "Customer Service"),
                            ("sales", "Sales"),
                            ("support", "Technical Support"),
                            ("booking", "Appointment Booking"),
                            ("faq", "FAQ Bot"),
                        ],
                        max_length=50,
                    ),
                ),
                ("system_prompt", models.TextField()),
                ("personality_traits", models.TextField()),
                ("suggested_knowledge", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="If private template",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={"db_table": "agent_templates",},
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("text", "Plain Text"),
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("url", "Website URL"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="knowledge_documents/%Y/%m/%d/"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="If document is from a URL"),
                ),
                ("content", models.TextField(help_text="Extracted text content")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash to detect duplicates",
                        max_length=64,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the document",
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                ("embeddings", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_documents",
                        to="agents.agent",
                    ),
                ),
            ],
            options={"db_table": "knowledge_documents", "ordering": ["-uploaded_at"],},
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["organization", "is_active"], name="agents_organiz_275400_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["agent", "is_processed"], name="knowledge_d_agent_i_331f82_idx"
            ),
        ),
    ]
