# Generated by Django 5.0 on 2025-08-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="business_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"monday": {"start": "09:00", "end": "17:00"}, ...}',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="out_of_hours_message",
            field=models.TextField(
                blank=True, help_text="Message when outside business hours", null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="voice_id",
            field=models.CharField(
                blank=True, help_text="ElevenLabs voice ID", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="voice_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Voice configuration settings",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="content_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA256 hash to detect duplicates",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata about the document",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="processing_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="If document is from a URL", null=True
            ),
        ),
    ]
