# Generated by Django 5.0 on 2025-08-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_agent_avatar_url_alter_agent_business_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="timezone",
            field=models.CharField(default="ET", max_length=50),
        ),
    ]
