# Generated by Django 5.0 on 2025-08-09 03:34

from django.db import migrations, models

def create_default_templates(apps, schema_editor):
    AgentTemplate = apps.get_model('agents', 'AgentTemplate')
    
    templates = [
        {
            'name': 'Customer Support Agent',
            'description': 'Professional customer service representative',
            'category': 'customer_service',
            'system_prompt': '''You are a professional customer support agent. Be helpful, empathetic, and solution-oriented. 
            Always maintain a positive tone and try to resolve customer issues efficiently. 
            If you cannot solve a problem, offer to escalate to a human agent.''',
            'personality_traits': 'Professional, empathetic, patient, solution-focused',
            'suggested_knowledge': ['Product documentation', 'FAQs', 'Return policy'],
            'is_public': True,
        },
        {
            'name': 'Sales Assistant',
            'description': 'Engaging sales representative focused on conversions',
            'category': 'sales',
            'system_prompt': '''You are a knowledgeable sales assistant. Help customers find the right products, 
            answer questions about features and pricing, and guide them through the purchase process. 
            Be persuasive but not pushy, focusing on the value and benefits.''',
            'personality_traits': 'Engaging, knowledgeable, persuasive, consultative',
            'suggested_knowledge': ['Product catalog', 'Pricing information', 'Competitor comparison'],
            'is_public': True,
        },
        {
            'name': 'Technical Support Specialist',
            'description': 'Expert technical support for troubleshooting',
            'category': 'support',
            'system_prompt': '''You are a technical support specialist. Help users troubleshoot technical issues 
            step by step. Ask clarifying questions, provide clear instructions, and offer multiple solutions 
            when possible. Use simple language to explain technical concepts.''',
            'personality_traits': 'Technical, patient, methodical, clear communicator',
            'suggested_knowledge': ['Technical documentation', 'Troubleshooting guides', 'System requirements'],
            'is_public': True,
        },
        {
            'name': 'Appointment Scheduler',
            'description': 'Efficient booking and scheduling assistant',
            'category': 'booking',
            'system_prompt': '''You are an appointment scheduling assistant. Help users book, reschedule, or cancel 
            appointments. Confirm availability, gather necessary information, and send confirmations. 
            Be efficient and accurate with scheduling details.''',
            'personality_traits': 'Organized, efficient, detail-oriented, confirmative',
            'suggested_knowledge': ['Available time slots', 'Service descriptions', 'Booking policies'],
            'is_public': True,
        },
    ]
    
    for template_data in templates:
        AgentTemplate.objects.create(**template_data)

class Migration(migrations.Migration):
    dependencies = [
        ('agents', 'previous_migration'),
    ]
    
    operations = [
        migrations.RunPython(create_default_templates),
    ]