# Generated by Django 5.0 on 2025-08-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_alter_agent_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="voice_id",
            field=models.CharField(
                default="21m00Tcm4TlvDq8ikWAM",
                help_text="ElevenLabs voice ID",
                max_length=100,
            ),
        ),
    ]
