# Generated by Django 5.0 on 2025-08-09 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("agents", "0001_initial"),
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("message", "Message"),
                            ("voice_minute", "Voice Minute"),
                            ("api_call", "API Call"),
                            ("storage", "Storage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="agents.agent",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conversations.conversation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "usage_logs",
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="usage_logs_organiz_a492da_idx",
                    )
                ],
            },
        ),
    ]
