# Generated by Django 5.0 on 2025-08-09 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("voice", "Voice Call"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("customer_phone", models.CharField(db_index=True, max_length=20)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "customer_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional customer information",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("waiting", "Waiting for Customer"),
                            ("ended", "Ended"),
                            ("handed_off", "Handed Off to Human"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("handed_off_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.IntegerField(default=0)),
                ("customer_message_count", models.IntegerField(default=0)),
                ("agent_message_count", models.IntegerField(default=0)),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True, help_text="Overall sentiment (-1 to 1)", null=True
                    ),
                ),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Customer satisfaction rating (1-5)",
                        null=True,
                    ),
                ),
                (
                    "first_response_time_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("resolution_time_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conversation context and state",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorization"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External system reference (e.g., Twilio Call SID)",
                        max_length=255,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="agents.agent",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-last_message_at", "-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("agent", "AI Agent"),
                            ("human", "Human Agent"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("location", "Location"),
                            ("template", "Template Message"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("media_url", models.URLField(blank=True)),
                ("media_mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Platform-specific metadata"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Message ID from external platform",
                        max_length=255,
                    ),
                ),
                ("detected_intent", models.CharField(blank=True, max_length=100)),
                ("detected_entities", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                (
                    "ai_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence score for generated responses",
                        null=True,
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="Number of tokens used for AI processing"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={"db_table": "messages", "ordering": ["created_at"],},
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["agent", "status"], name="conversatio_agent_i_1e4d27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["customer_phone", "status"],
                name="conversatio_custome_2c337a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["started_at", "status"], name="conversatio_started_5de7ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="messages_convers_3ebb41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["external_id"], name="messages_externa_2ca868_idx"
            ),
        ),
    ]
