# Generated by Django 5.0 on 2025-08-15 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_alter_agent_timezone"),
        ("conversations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation", options={"ordering": ["-last_message_at"]},
        ),
        migrations.RemoveIndex(
            model_name="conversation", name="conversatio_agent_i_1e4d27_idx",
        ),
        migrations.RemoveIndex(
            model_name="conversation", name="conversatio_custome_2c337a_idx",
        ),
        migrations.RemoveIndex(
            model_name="conversation", name="conversatio_started_5de7ba_idx",
        ),
        migrations.AlterField(
            model_name="message",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional conversation metadata"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["agent", "status", "started_at"],
                name="conversatio_agent_i_4df432_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["customer_phone", "started_at"],
                name="conversatio_custome_8295f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["channel", "started_at"], name="conversatio_channel_f14583_idx"
            ),
        ),
    ]
