# Generated by Django 5.0 on 2025-08-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_alter_conversation_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation", old_name="context", new_name="metadata",
        ),
    ]
