# Generated by Django 5.0 on 2025-08-20 03:19

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_rename_context_conversation_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2025, 8, 20, 3, 19, 18, 161897, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
