# Generated by Django 5.0 on 2025-08-22 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0004_alter_conversation_started_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2025, 8, 22, 2, 54, 54, 420695, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
